#!/usr/bin/env node
/**
 * copy-icons — pulls the SVGs the DS actually uses out of the canonical FAMS V5
 * icon library and generates the ui-kit icon registry.
 *
 * Source (read-only): /Users/apple/Desktop/Icons  (1,247 SVGs, Untitled-UI names
 * + custom FAMS glyphs). Override with ICONS_SRC=<dir>.
 *
 * Writes into packages/ui-kit/src/icons/:
 *   glyphs.tsx       one React component per glyph, all in ONE module (fill -> currentColor)
 *   registry.ts      name -> lazy-free component map + aliases
 *   named.ts         PascalCase compat exports (the old lucide-react names)
 *   (index.ts and Icon.tsx are hand-authored, not generated)
 *
 * `--all` copies the WHOLE library instead of just the mapped subset, so the
 * full set can be pulled later without editing this script.
 *
 * Run: node scripts/icons/copy-icons.mjs
 *
 * Vendored into this repo (it used to live in a run-plan folder in another
 * workspace, pointing at that workspace's checkout) so regenerating the icon
 * set is a first-class, repeatable repo operation.
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, '../..')
const SRC = process.env.ICONS_SRC || '/Users/apple/Desktop/ju/Icons'
const OUT = join(REPO, 'packages/ui-kit/src/icons')
const ALL = process.argv.includes('--all')

const map = JSON.parse(readFileSync(join(HERE, 'icon-map.json'), 'utf8'))
const wanted = ALL
  ? readdirSync(SRC).filter((f) => f.endsWith('.svg')).map((f) => f.slice(0, -4))
  : [...new Set([...Object.values(map.lucide), ...Object.values(map.metadataAliases), ...map.extras])]

/** kebab/space/& filename -> a valid PascalCase identifier. */
const ident = (n) =>
  'Svg' + n.replace(/[^a-zA-Z0-9]+/g, ' ').trim().split(' ')
    .map((p) => (/^\d/.test(p) ? '_' + p : p[0].toUpperCase() + p.slice(1)).replace(/^_?(.)/, (m) => m))
    .join('')

/** SVG file -> JSX body. Hard-coded hex fills become currentColor so tokens drive colour. */
function toJsx(svg) {
  let body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
  body = body
    .replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"')
    .replace(/stroke="#[0-9a-fA-F]{3,8}"/g, 'stroke="currentColor"')
    .replace(/([a-z]+)-([a-z])([a-zA-Z-]*)=/g, (m, a, b, c) =>
      `${a}${b.toUpperCase()}${c.replace(/-([a-z])/g, (_, d) => d.toUpperCase())}=`)
    .replace(/<!--[\s\S]*?-->/g, '')
    .trim()
  return body
}

rmSync(join(OUT, 'svg'), { recursive: true, force: true })
mkdirSync(OUT, { recursive: true })

// ---- glyphs.tsx --------------------------------------------------------
// ONE module, not one file per glyph. Tree-shaking is per-EXPORT for both
// esbuild and rollup, so an app that uses six glyphs still ships six — but a
// single module keeps the transform cost (dev server, vitest) at one file
// instead of ~200, which is what a per-file layout cost us in v5-templates'
// suite (a 17s module-load timeout on the first file to touch the barrel).
const entries = []
let glyphs =
  `// GENERATED by scripts/icons/copy-icons.mjs from the canonical FAMS V5\n` +
  `// icon library. Do not edit by hand — re-run the script instead.\n` +
  `import type { IconSvgProps } from './glyph-props'\n`

for (const name of wanted.sort()) {
  const file = join(SRC, `${name}.svg`)
  if (!existsSync(file)) throw new Error(`copy-icons: missing source SVG "${name}.svg" in ${SRC}`)
  const id = ident(name)
  const jsx = toJsx(readFileSync(file, 'utf8'))
  glyphs +=
    `\n/** \`${name}\` */\n` +
    `export function ${id}({ children, size = 24, ...props }: IconSvgProps) {\n` +
    `  return (\n` +
    `    <svg\n` +
    `      viewBox="0 0 24 24"\n` +
    `      width={size}\n` +
    `      height={size}\n` +
    `      fill="none"\n` +
    `      xmlns="http://www.w3.org/2000/svg"\n` +
    `      data-icon=${JSON.stringify(name)}\n` +
    `      {...props}\n` +
    `    >\n` +
    `      ${jsx.replace(/\n/g, '\n      ')}\n` +
    `      {children}\n` +
    `    </svg>\n  )\n}\n`
  entries.push({ name, id })
}
writeFileSync(join(OUT, 'glyphs.tsx'), glyphs)

// ---- registry.ts -------------------------------------------------------
const aliasPairs = Object.entries(map.metadataAliases).filter(([k, v]) => k !== v)
writeFileSync(
  join(OUT, 'registry.ts'),
  `// GENERATED by scripts/icons/copy-icons.mjs. Do not edit by hand.\n` +
    `import type { ComponentType } from 'react'\n` +
    `import type { IconSvgProps } from './glyph-props'\n\n` +
    `/** Every glyph is a plain SVG component — the shape the old icon set also had. */\n` +
    `export type IconGlyph = ComponentType<IconSvgProps>\n\n` +
    `import {\n` + entries.map((e) => `  ${e.id},`).join('\n') + `\n} from './glyphs'\n` +
    `\n\n/** Canonical library filename -> glyph. */\nexport const ICON_REGISTRY = {\n` +
    entries.map((e) => `  ${JSON.stringify(e.name)}: ${e.id},`).join('\n') +
    `\n} as const satisfies Record<string, IconGlyph>\n\n` +
    `export type IconName = keyof typeof ICON_REGISTRY\n\n` +
    `/** Legacy/metadata-authored names -> canonical library filename. */\n` +
    `export const ICON_ALIASES: Record<string, IconName> = {\n` +
    aliasPairs.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n') +
    `\n}\n`,
)

// ---- named.ts ----------------------------------------------------------
writeFileSync(
  join(OUT, 'named.ts'),
  `// GENERATED by scripts/icons/copy-icons.mjs. Do not edit by hand.\n` +
    `//\n// Compat layer: the PascalCase names the DS used to import from\n` +
    `// 'lucide-react', now bound to the canonical FAMS V5 glyph each one maps to\n` +
    `// (see plan/.../specs/icons/icon-map.json). Kept OUT of the ui-kit barrel —\n` +
    `// several names (Map, List, Gauge, File, Image) would collide with real\n` +
    `// ui-kit exports — so it ships as the '@fams/ui-kit/icons' subpath.\n` +
    Object.entries(map.lucide)
      .sort()
      .map(([lu, lib]) => `export { ${ident(lib)} as ${lu} } from './glyphs'`)
      .join('\n') +
    `\n`,
)

console.log(`copy-icons: ${entries.length} glyphs -> ${OUT}${ALL ? ' (FULL LIBRARY)' : ''}`)
