import * as React from 'react';
import type { ModuleConfig } from '@ds/components/app-shell';
import { EventsView, EventDetailSheet, EventAssignSheet, DEFAULT_ASSIGNEES } from '@ds/components/events';
import type { EventItem } from '@ds/components/events';
import type { FeedEntry } from '@ds/components/widgets';
import { Announcement01 } from '@ds/icons';

/**
 * Events BLOCK — all events generated by entities (telematics/ops): Over Speeding,
 * Harsh Braking, Idle Warning, Engine Off, Black Spot Alarm, Harsh Turning, Fuel
 * Theft, Excess Idling… Hybrid View: date-grouped expandable cards beside a map;
 * expanding a card highlights the event on the map with a contextual chart widget;
 * "View Details" opens the full side sheet (fields + route map + speed chart +
 * timeline). Backed by DS `EventsView` + `EventDetailSheet`.
 *
 * DYNAMIC: `events: EventItem[]` + `eventStyles` are data — any entity's event
 * stream adapts by config. Brand = FAMS blue; green/amber/red = genuine
 * criticality. See events.block.md + kb 02-frames-pipelines/11-events.md.
 */

const speed = (peak: number) => Array.from({ length: 17 }, (_, i) => ({ t: `11:${String(i).padStart(2, '0')}`, speed: i < 9 ? 55 + i * 3 : i < 15 ? peak - Math.abs(12 - i) * 6 : 70 - (i - 15) * 8 }));
const det = (limit: number, peak: number) => [
  { label: 'Peak Speed', value: `${peak} km/h` }, { label: 'Speed Limit', value: `${limit} km/h` },
  { label: 'Duration', value: '2m 14s' }, { label: 'Distance Over Limit', value: '1.2 km' }, { label: 'Vehicle Type', value: 'Container' },
];

const EVENTS: EventItem[] = [
  { id: 'EV-2323', type: 'Harsh Braking', title: 'Harsh Braking', subtitle: 'Aggressive throttle · driver flag', criticality: 'critical', timeLabel: '15m ago', dateGroup: 'Today', vehicle: 'FM-882', person: 'Ahmed Ali', zone: 'Zone A', location: 'Central Tower, Al Seyouh', metric: { value: '−9.4m/s²' }, position: [25.20, 55.33], status: 'Open', details: det(100, 118) },
  { id: 'EV-2325', type: 'Over Speeding', title: 'Over Speeding', subtitle: 'Speed exceeded the zone limit', criticality: 'critical', timeLabel: '55m ago', dateGroup: 'Today', vehicle: 'TU-5983', person: 'Abubakar R.', zone: 'Zone A', location: 'Central Tower, Al Seyouh', metric: { value: '120 km/h' }, position: [25.22, 55.31], status: 'Open', details: det(100, 120), speedSeries: speed(112), speedLimit: 100, breach: [9, 15] },
  { id: 'EV-2326', type: 'Engine Off', title: 'Engine Off', subtitle: 'Stopped at Central Tower', criticality: 'info', timeLabel: '12:23 PM', dateGroup: 'Today', vehicle: 'TU-5983', person: 'Abubakar R.', zone: 'Zone A', location: 'Central Tower, Al Seyouh', position: [25.17, 55.38], status: 'Assigned', details: det(100, 0), assignee: 'Ahmed Ali', assignedToMe: true },
  { id: 'EV-2329', type: 'Harsh Turning', title: 'Harsh Turning', subtitle: 'Sharp turn at speed on MM Alram', criticality: 'warning', timeLabel: '09:24 AM', dateGroup: 'Yesterday', vehicle: 'TU-5983', person: 'Abubakar R.', zone: 'Zone A', location: 'Central Tower, Al Seyouh', metric: { value: '0.71 g' }, position: [25.11, 55.37], status: 'Open', details: det(100, 0) },
];

const TIMELINE: FeedEntry[] = [
  { kind: 'system', id: 't1', dateGroup: '22 Jun, 2026', author: 'System', text: 'Event Generated', timestamp: '11:20 pm' },
  { kind: 'system', id: 't2', author: 'Khalid Al-Mansoori', text: 'Update Status', timestamp: '01:24 am', chip: { label: 'Open → Under Inspection', tone: 'warning' } },
  { kind: 'comment', id: 't3', author: 'Ali Raza', avatarFallback: 'AR', timestamp: '03:24 am', text: 'Submitted justification for review.' },
];

/** the signed-in user, for resolving "assigned to me" — matches Ahmed Ali in DEFAULT_ASSIGNEES. */
const SELF_ASSIGNEE_ID = 'usr-ahmed-ali';

function EventsModule() {
  const [events, setEvents] = React.useState<EventItem[]>(EVENTS);
  const [detail, setDetail] = React.useState<EventItem | null>(null);
  const [assignFor, setAssignFor] = React.useState<EventItem[] | null>(null);
  const byIds = (ids: string[]) => events.filter((e) => ids.includes(e.id));
  const escalate = (ids: string[]) => setEvents((es) => es.map((e) => (ids.includes(e.id) ? { ...e, status: 'Escalated', statusTone: 'var(--status-error)' } : e)));
  const assign = (assigneeId: string, _note: string, eventIds: string[]) => {
    const assigneeName = DEFAULT_ASSIGNEES.find((a) => a.id === assigneeId)?.name ?? assigneeId;
    setEvents((es) => es.map((e) => (eventIds.includes(e.id) ? { ...e, assignee: assigneeName, status: 'Assigned', assignedToMe: assigneeId === SELF_ASSIGNEE_ID } : e)));
    setAssignFor(null);
  };
  return (
    <>
      <EventsView
        events={events}
        onViewDetails={setDetail}
        onAddComment={(e) => setDetail(e)}
        onAssign={(e) => setAssignFor([e])}
        onBulkAssign={(ids) => setAssignFor(byIds(ids))}
        onEscalate={(e) => escalate([e.id])}
        onBulkEscalate={escalate}
        onBulkUpdateStatus={(ids) => setEvents((es) => es.map((e) => (ids.includes(e.id) ? { ...e, status: 'Under Inspection', statusTone: 'var(--status-warning)' } : e)))}
      />
      <EventDetailSheet open={!!detail} event={detail} timeline={TIMELINE} onOpenChange={(o) => { if (!o) setDetail(null); }} />
      <EventAssignSheet
        open={!!assignFor}
        selectedEvents={assignFor ?? undefined}
        onOpenChange={(o) => { if (!o) setAssignFor(null); }}
        onAssign={assign}
      />
    </>
  );
}

export const eventsBlock: ModuleConfig = {
  id: 'events',
  type: 'dashboard',
  label: 'Events',
  icon: Announcement01,
  tabKind: 'instance',
  defaultTabId: 'hybrid',
  tabs: [
    { id: 'hybrid', label: 'Hybrid View', icon: Announcement01, render: () => <EventsModule /> },
    { id: 'list', label: 'List View', icon: Announcement01, render: () => <EventsModule /> },
    { id: 'map', label: 'Map View', icon: Announcement01, render: () => <EventsModule /> },
  ],
};
