import type { EntityConfig, EntityRecord } from '@fams/v5-composer'

/**
 * cockpit-fixtures.ts — a cockpit-lens module fixture for tests and the
 * showcase demo (same role `live-fixtures.ts` plays for the live hybrid).
 * Generic ops vocabulary only; geometry lives in this data file, never in
 * components (SPEC §3 convention). Coordinates are Doha-ish.
 */
export const cockpitConfig: EntityConfig = {
  code: 'ops-queue',
  name: 'Dispatch Queue',
  uidPrefix: 'JB',
  systemcolumns: [
    { id: 'fld_title', col: 'title', name: 'Job', type: 'SmallText', required: true },
    {
      id: 'fld_status',
      col: 'status',
      name: 'Status',
      type: 'SingleSelect',
      listValues: ['Scheduled', 'Ongoing', 'Delayed', 'Action Required', 'Completed'],
    },
    { id: 'fld_asset', col: 'systemcol1', name: 'Asset', type: 'SmallText' },
    { id: 'fld_assignee', col: 'systemcol2', name: 'Assignee', type: 'SmallText' },
    { id: 'fld_progress', col: 'systemcol3', name: 'Progress', type: 'Numeric' },
    { id: 'fld_progress_label', col: 'systemcol4', name: 'Progress Detail', type: 'SmallText' },
    { id: 'fld_planned', col: 'systemcol5', name: 'Planned', type: 'SmallText' },
    { id: 'fld_actual', col: 'systemcol6', name: 'Actual', type: 'SmallText' },
    { id: 'fld_plan', col: 'systemcol7', name: 'Plan', type: 'SmallText' },
    { id: 'fld_risk', col: 'systemcol8', name: 'Risk Note', type: 'SmallText' },
    { id: 'fld_risk_tone', col: 'systemcol9', name: 'Risk Tone', type: 'SmallText' },
    { id: 'fld_lat', col: 'systemcol10', name: 'Latitude', type: 'Numeric' },
    { id: 'fld_lng', col: 'systemcol11', name: 'Longitude', type: 'Numeric' },
    { id: 'fld_contact', col: 'systemcol12', name: 'Contact', type: 'Phone' },
    { id: 'fld_delay', col: 'systemcol13', name: 'Delay', type: 'SmallText' },
    { id: 'fld_shift', col: 'systemcol14', name: 'Shift', type: 'SingleSelect', listValues: ['Morning', 'Evening', 'Night'] },
    { id: 'fld_standby', col: 'systemcol15', name: 'Standby', type: 'SmallText' },
  ],
  listcolumns: [
    { id: 'fld_title', col: 'title' },
    { id: 'fld_status', col: 'status' },
  ],
  uiConfig: {
    statusList: [
      { id: 'sts_sched', key: 'Scheduled', label: 'Scheduled', color: 'var(--color-muted-foreground)' },
      { id: 'sts_ongoing', key: 'Ongoing', label: 'Ongoing', color: 'var(--color-info)' },
      { id: 'sts_delayed', key: 'Delayed', label: 'Delayed', color: 'var(--color-warning)' },
      { id: 'sts_action', key: 'Action Required', label: 'Action Required', color: 'var(--color-destructive)' },
      { id: 'sts_done', key: 'Completed', label: 'Completed', color: 'var(--color-success)' },
    ],
    map: {
      latCol: 'systemcol10',
      lngCol: 'systemcol11',
      plateCol: 'systemcol1',
      driverCol: 'systemcol2',
    },
    cockpit: {
      alert: {
        text: '3 routes for the next shift are at risk of failing',
        countdown: '2h 14m to shift start',
        tone: 'danger',
      },
      kpis: [
        { id: 'kpi-scheduled', label: 'Scheduled', countStatus: 'Scheduled', detailColumns: ['title', 'status', 'systemcol1', 'systemcol2'] },
        { id: 'kpi-ongoing', label: 'Ongoing', countStatus: 'Ongoing', accent: 'info', detailColumns: ['title', 'status', 'systemcol2'] },
        { id: 'kpi-delayed', label: 'Delayed', countStatus: 'Delayed', accent: 'warning', detailColumns: ['title', 'status', 'systemcol5', 'systemcol6'] },
        { id: 'kpi-fulfillment', label: 'Fulfillment Rate', value: '96%', accent: 'success', badge: { label: '+2 vs Yest.', tone: 'up' }, detailColumns: ['title', 'status', 'systemcol4'] },
        { id: 'kpi-completed', label: 'Completed', countStatus: 'Completed', accent: 'success' },
        { id: 'kpi-action', label: 'Action Required', countStatus: 'Action Required', accent: 'danger', badge: { label: 'View Details', tone: 'link' }, opens: 'issues', detailColumns: ['title', 'status', 'systemcol8'] },
      ],
      filters: [
        { id: 'flt-shift', label: 'Shift', col: 'systemcol14' },
        { id: 'flt-status', label: 'Status', col: 'status' },
        { id: 'flt-zone', label: 'Zone', placeholder: true, options: ['North', 'South'] },
      ],
      actions: [
        { id: 'act-broadcast', label: 'Broadcast', icon: 'broadcast', kind: 'toast', message: 'Broadcast sent' },
        {
          id: 'act-quick',
          label: 'Quick Actions',
          icon: 'actions',
          kind: 'menu',
          items: [{ id: 'qa-reassign', label: 'Bulk reassign', message: 'Bulk reassign queued' }],
        },
        { id: 'act-export', label: 'Export', icon: 'export', primary: true, kind: 'toast', message: 'Export ready' },
      ],
      popup: {
        contactCol: 'systemcol12',
        commands: [
          { id: 'cmd-immobilize', label: 'Immobilize', message: 'Immobilize command queued', tone: 'warning' },
          { id: 'cmd-mobilize', label: 'Mobilize', message: 'Mobilize command sent' },
        ],
      },
      flows: {
        callLabel: 'Call Assignee',
        report: {
          label: 'Report Breakdown',
          typeLabel: 'Breakdown Type',
          typeOptions: ['Mechanical', 'Electrical', 'Tyre'],
          dispatchLabel: 'Dispatch a replacement',
          targetStatus: 'Action Required',
          successTitle: 'Breakdown Reported',
          successDescription: 'The route was flagged for attention.',
        },
        issues: {
          title: 'Current Shift Issues',
          status: 'Action Required',
          reasonCol: 'systemcol8',
          suggestLabel: 'Suggest Nearby Routes',
        },
        assign: { title: 'Nearby Routes', assignLabel: 'Assign', successTitle: 'Route assigned' },
        replace: {
          label: 'Suggest Replacement',
          title: 'Replace Vehicle & Assignee',
          currentCols: ['systemcol1'],
          standbyCols: ['systemcol15'],
          confirmLabel: 'Confirm Replacement',
          resolveStatus: 'Ongoing',
          successTitle: 'Replacement confirmed',
        },
      },
      queue: {
        subtitleCol: 'systemcol1',
        avatarCol: 'systemcol2',
        deltaCol: 'systemcol13',
        progressCol: 'systemcol3',
        progressLabelCol: 'systemcol4',
        plannedCol: 'systemcol5',
        actualCol: 'systemcol6',
        metaCols: ['systemcol7'],
        bannerCol: 'systemcol8',
        bannerToneCol: 'systemcol9',
        searchCols: ['systemcol2'],
      },
      routes: { plannedCol: 'plannedPath', actualCol: 'actualPath' },
      panels: [
        {
          id: 'fleet',
          title: 'Fleet Availability',
          icon: 'group',
          filter: { label: 'All Assets', options: ['Owned', 'Contracted'] },
          stats: [
            { label: 'Available', value: 18 },
            { label: 'In Service', value: 4 },
          ],
          countByCol: 'status',
          toneMap: {
            Scheduled: 'neutral',
            Ongoing: 'info',
            Delayed: 'warning',
            'Action Required': 'danger',
            Completed: 'success',
          },
        },
        {
          id: 'workforce',
          title: 'Workforce Readiness',
          icon: 'people',
          rows: [
            { label: 'On Duty', count: 22, tone: 'success' },
            { label: 'On Break', count: 5, tone: 'warning' },
            { label: 'Off Duty', count: 3, tone: 'neutral' },
          ],
        },
      ],
    },
  },
}

export const cockpitRecords: EntityRecord[] = [
  {
    id: 'jb-1',
    uniqueidentifier: 'JB-1001',
    title: 'Downtown Service Plan',
    status: 'Ongoing',
    systemcol1: 'AD 41273',
    systemcol2: 'Lina Farouk',
    systemcol3: 64,
    systemcol4: '9/14 tasks · 64%',
    systemcol5: 'Planned 06:00 – 14:00',
    systemcol6: 'Actual 06:04',
    systemcol7: 'Route A · Morning',
    systemcol12: '+974 50 000 0001',
    systemcol14: 'Morning',
    systemcol10: 25.3239,
    systemcol11: 51.4273,
    plannedPath: [
      [54.37, 24.45],
      [54.38, 24.455],
      [54.39, 24.452],
    ],
    actualPath: [
      [54.37, 24.45],
      [54.378, 24.457],
      [54.389, 24.4535],
    ],
  },
  {
    id: 'jb-2',
    uniqueidentifier: 'JB-1002',
    title: 'Harbor Loop',
    status: 'Delayed',
    systemcol1: 'AD 55810',
    systemcol2: 'Omar Haddad',
    systemcol3: 32,
    systemcol4: '4/12 tasks · 32%',
    systemcol5: 'Planned 06:30 – 14:30',
    systemcol6: 'Actual 07:02 · +32 min',
    systemcol7: 'Route B · Morning',
    systemcol8: 'SLA at risk on 2 stops',
    systemcol9: 'warning',
    systemcol12: '+974 50 000 0002',
    systemcol13: 'Running 32 min late',
    systemcol14: 'Morning',
    systemcol10: 25.35,
    systemcol11: 51.4,
  },
  {
    id: 'jb-3',
    uniqueidentifier: 'JB-1003',
    title: 'Airport Corridor',
    status: 'Action Required',
    systemcol1: 'AD 20194',
    systemcol2: 'Sara Novak',
    systemcol3: 12,
    systemcol4: '1/9 tasks · 12%',
    systemcol5: 'Planned 07:00 – 15:00',
    systemcol6: 'Actual 07:05',
    systemcol7: 'Route C · Morning',
    systemcol8: 'Asset reported a fault — replacement needed',
    systemcol9: 'danger',
    systemcol12: '+974 50 000 0003',
    systemcol14: 'Morning',
    systemcol15: 'Standby AD 90001',
    systemcol10: 25.3,
    systemcol11: 51.7,
  },
  {
    id: 'jb-4',
    uniqueidentifier: 'JB-1004',
    title: 'North Industrial Sweep',
    status: 'Scheduled',
    systemcol1: 'AD 88321',
    systemcol2: 'Deniz Aksoy',
    systemcol5: 'Planned 14:00 – 22:00',
    systemcol7: 'Route D · Evening',
    systemcol14: 'Evening',
    systemcol10: 25.39,
    systemcol11: 51.46,
  },
  {
    id: 'jb-5',
    uniqueidentifier: 'JB-1005',
    title: 'Corniche Line',
    status: 'Completed',
    systemcol1: 'AD 10457',
    systemcol2: 'Mia Torres',
    systemcol3: 100,
    systemcol4: '11/11 tasks · 100%',
    systemcol5: 'Planned 22:00 – 06:00',
    systemcol6: 'Actual 22:00 – 05:41',
    systemcol7: 'Route E · Night',
    systemcol14: 'Night',
    systemcol10: 25.34,
    systemcol11: 51.38,
  },
]
