// @ts-check
/**
 * Customization-debt dashboard (tenant-model.md: "Dashboard tracks per-tenant
 * customization debt"; decision #16/#17). Derives a DETERMINISTIC markdown
 * report from repo state so it can be committed and byte-compared in CI (same
 * staleness pattern as `resolved/`): if `docs/debt-dashboard.md` does not equal
 * `buildDebtDashboard(root)`, `demo check` fails.
 *
 * It tracks four things:
 *   1. per-tenant delta counts per module (how customized each tenant is);
 *   2. outstanding capture debt — COMMITTED `*.override.json` records (capture
 *      ladder ②, merged as flagged debt) plus any local `*.ops.proposed.json`
 *      (capture punted, uncommitted) — both un-canonicalized debt to clean up;
 *   3. override-flagged modules (`overrides/screens/<m>` — bespoke UI screens);
 *   4. promotion candidates — the same op SHAPE (op type + target id) appearing
 *      in ≥2 tenants (tenant-model.md: "Lint flags ≥2–3 tenants carrying
 *      near-identical ops → promote to core").
 */
import { readJson, paths, listTenants, licensedModules, readDeltas, overrideModules, proposedModules, overrideRecordModules } from './repo.mjs';

/** The stable target id an op acts on — the key half of an op's "shape". */
function opTargetId(op) {
  switch (op.op) {
    case 'addField': return op.field?.id ?? '?';
    case 'addStage': return op.stage?.id ?? '?';
    case 'addTab': return op.tab?.id ?? '?';
    case 'setFieldProp': return `${op.id}.${op.prop}`;
    case 'reorderTabs': return '(order)';
    default: return op.id ?? '?';
  }
}

/**
 * Gather debt facts for every tenant. Pure (no IO side effects beyond reads).
 * @returns {{
 *   tenants: { tenant: string, modules: { module: string, deltaCount: number }[],
 *              proposed: string[], overrideRecords: string[], overrides: string[] }[],
 *   candidates: { shape: string, module: string, op: string, target: string, tenants: string[] }[],
 * }}
 */
export function gatherDebt(root) {
  const tenants = [];
  /** shape → { module, op, target, tenants:Set } */
  const shapes = new Map();

  for (const tenant of listTenants(root)) {
    let manifest;
    try { manifest = readJson(paths.tenantManifest(root, tenant)); }
    catch { continue; }
    const modules = licensedModules(manifest);
    const moduleRows = [];
    for (const m of modules) {
      const { ops } = readDeltas(root, tenant, m);
      moduleRows.push({ module: m, deltaCount: ops.length });
      for (const op of ops) {
        const target = opTargetId(op);
        const shape = `${m}:${op.op}:${target}`;
        const entry = shapes.get(shape) ?? { module: m, op: op.op, target, tenants: new Set() };
        entry.tenants.add(tenant);
        shapes.set(shape, entry);
      }
    }
    tenants.push({
      tenant,
      modules: moduleRows,
      proposed: proposedModules(root, tenant),
      overrideRecords: overrideRecordModules(root, tenant),
      overrides: overrideModules(root, tenant),
    });
  }

  const candidates = [...shapes.entries()]
    .filter(([, e]) => e.tenants.size >= 2)
    .map(([shape, e]) => ({ shape, module: e.module, op: e.op, target: e.target, tenants: [...e.tenants].sort() }))
    .sort((a, b) => a.shape.localeCompare(b.shape));

  return { tenants, candidates };
}

/**
 * Render the debt facts as deterministic markdown (trailing newline, sorted
 * throughout — byte-stable so CI can compare it against the committed file).
 */
export function buildDebtDashboard(root) {
  const { tenants, candidates } = gatherDebt(root);
  const out = [];
  out.push('# Customization Debt Dashboard');
  out.push('');
  out.push('> Generated by `pnpm demo debt` (decision #17). Do not hand-edit — `demo check` fails if this file is stale. Re-run after changing any tenant delta, proposal, or override.');
  out.push('');

  // 1. Per-tenant delta counts per module.
  out.push('## Per-tenant delta counts');
  out.push('');
  out.push('| Tenant | Module | Deltas | Proposals | Overrides |');
  out.push('| --- | --- | ---: | --- | --- |');
  for (const t of tenants) {
    const mods = t.modules.length ? t.modules : [{ module: '(none)', deltaCount: 0 }];
    for (const m of mods) {
      // A committed override record is stronger debt than a local proposal.
      const proposed = t.overrideRecords.includes(m.module)
        ? 'override (flagged debt)'
        : t.proposed.includes(m.module) ? 'needs-canonicalization' : '—';
      const override = t.overrides.includes(m.module) ? 'override-flagged' : '—';
      out.push(`| ${t.tenant} | ${m.module} | ${m.deltaCount} | ${proposed} | ${override} |`);
    }
  }
  out.push('');

  // 2. Outstanding capture debt — committed override records + local proposals.
  out.push('## Outstanding capture proposals');
  out.push('');
  const anyProposed = tenants.some((t) => t.proposed.length);
  const anyOverrideRec = tenants.some((t) => t.overrideRecords.length);
  if (!anyProposed && !anyOverrideRec) {
    out.push('None. Every locked-in edit has been canonicalized to typed deltas.');
  } else {
    out.push('| Tenant | Module | Kind | File |');
    out.push('| --- | --- | --- | --- |');
    for (const t of tenants) {
      for (const m of t.overrideRecords) {
        out.push(`| ${t.tenant} | ${m} | override (merged as flagged debt) | \`tenants/${t.tenant}/deltas/${m}.override.json\` |`);
      }
      for (const m of t.proposed) {
        out.push(`| ${t.tenant} | ${m} | proposed (uncommitted, local) | \`tenants/${t.tenant}/deltas/${m}.ops.proposed.json\` |`);
      }
    }
  }
  out.push('');

  // 3. Override-flagged modules.
  out.push('## Override-flagged modules');
  out.push('');
  const anyOverride = tenants.some((t) => t.overrides.length);
  if (!anyOverride) {
    out.push('None. No tenant carries a bespoke `overrides/screens/` module.');
  } else {
    out.push('| Tenant | Module |');
    out.push('| --- | --- |');
    for (const t of tenants) {
      for (const m of t.overrides) out.push(`| ${t.tenant} | ${m} |`);
    }
  }
  out.push('');

  // 4. Promotion candidates.
  out.push('## Promotion candidates (same op shape in ≥2 tenants)');
  out.push('');
  if (!candidates.length) {
    out.push('None. No op shape is shared across tenants yet.');
  } else {
    out.push('| Module | Op | Target | Tenants |');
    out.push('| --- | --- | --- | --- |');
    for (const c of candidates) {
      out.push(`| ${c.module} | ${c.op} | \`${c.target}\` | ${c.tenants.join(', ')} |`);
    }
  }
  out.push('');

  return out.join('\n');
}
