import * as React from 'react';
import * as Icons from '../../icons';
import { cn } from '../utils/cn';
import { Popover, PopoverTrigger, PopoverContent, Checkbox } from '../primitives';
import { LeafletMap } from '../map';
import type { LatLng, LeafletMapHandle } from '../map';
import { LineChart } from '../data-viz';

/**
 * EventsView — the Events module Hybrid View (FAMS V5 Launch Pad, Figma
 * W2z46FvC6aOdzOHDc3rqD5 · 4292-25771). All events generated by entities, listed
 * date-grouped beside a map. Clicking a card EXPANDS it inline (details grid +
 * Add Comment/Assign/Escalate/View Details) and highlights the event on the map
 * (flyTo + emphasised marker) with a contextual chart widget. A search bar and a
 * severity tab bar (All/Critical/High/Normal/Assigned to me) sit above the
 * existing filter chips; each row carries a select checkbox and, once ≥1 row is
 * selected, a floating bulk-action bar (Assign/Escalate/Update Status) appears.
 * The map carries a small severity show/hide toggle. Brand = FAMS blue;
 * green/amber/red are genuine criticality status. Config-driven: `events`,
 * `eventStyles`, callbacks.
 */

export type EventCriticality = 'critical' | 'warning' | 'info';
export interface EventDetailField { label: string; value: React.ReactNode }
export interface EventSpeedPoint { t: string; speed: number }

export interface EventItem {
  id: string;
  type: string;
  title: string;
  subtitle: string;
  criticality: EventCriticality;
  timeLabel: string;
  dateGroup: string;
  vehicle: string;
  person: string;
  zone: string;
  location: string;
  metric?: { value: string; tone?: string };
  position: LatLng;
  status: string;
  statusTone?: string;
  details: EventDetailField[];
  /** contextual chart (speed over time) for the map widget + detail. */
  speedSeries?: EventSpeedPoint[];
  speedLimit?: number;
  /** [startIdx,endIdx] over speedSeries to shade the breach window. */
  breach?: [number, number];
  /** true when currently assigned to the signed-in user — powers the "Assigned to me" severity tab. */
  assignedToMe?: boolean;
  /** display name of the current assignee, if any — shown as an "Assigned To" row once set. */
  assignee?: string;
}

export interface EventStyle { icon: React.ReactNode; color: string }
export interface EventsViewProps {
  events: EventItem[];
  eventStyles?: Record<string, EventStyle>;
  center?: LatLng;
  zoom?: number;
  onViewDetails?: (e: EventItem) => void;
  /** expanded-card action buttons (Add Comment · Assign · Escalate — left of View Details). */
  onAddComment?: (e: EventItem) => void;
  onAssign?: (e: EventItem) => void;
  onEscalate?: (e: EventItem) => void;
  /** floating bulk bar shown once ≥1 row checkbox is selected. */
  onBulkAssign?: (ids: string[]) => void;
  onBulkEscalate?: (ids: string[]) => void;
  onBulkUpdateStatus?: (ids: string[]) => void;
  /** search over title/subtitle/vehicle/person/zone/location — controlled if both are given, else internal state. */
  searchQuery?: string;
  onSearchChange?: (q: string) => void;
  className?: string;
}

const CRIT = { critical: 'var(--status-error)', warning: 'var(--status-warning)', info: 'var(--primary)' } as const;

/** Map an event type to a canonical FAMS event-glyph name (see src/icons/event-icons). */
function eventIconName(type: string): string {
  const t = type.toLowerCase();
  if (t.includes('overspeed') || t.includes('over speed') || t.includes('speeding')) return 'Overspeed';
  if (t.includes('brak')) return 'Harsh Breaking';
  if (t.includes('accel')) return 'Harsh Acceleration';
  if (t.includes('corner')) return 'Harsh Cornering';
  if (t.includes('turn')) return 'Harsh Turning';
  if (t.includes('excess idl')) return 'Excess Idle';
  if (t.includes('idl')) return 'Idle';
  if (t.includes('engine off')) return 'Engine Off';
  if (t.includes('engine on')) return 'Engine On';
  if (t.includes('black')) return 'Black Spot';
  if (t.includes('fuel theft')) return 'Fuel Theft';
  if (t.includes('fuel drop')) return 'Fuel Drop';
  if (t.includes('fuel fill') || t.includes('refuel')) return 'Fuel Fill';
  if (t.includes('zone in')) return 'Zone In';
  if (t.includes('zone out')) return 'Zone Out';
  if (t.includes('zone stay')) return 'Zone Stay';
  if (t.includes('door open')) return 'Door Open';
  if (t.includes('door close')) return 'Door Close';
  if (t.includes('tamper')) return 'Tracker Tampering Alarm';
  if (t.includes('stop')) return 'Stop';
  if (t.includes('trip')) return 'Trip';
  if (t.includes('collision')) return 'Forward Collision Warning';
  if (t.includes('fatigue')) return 'Fatigue Driving';
  if (t.includes('distract')) return 'Distracted Driver';
  return type;
}

/** The card tile: prefer the canonical FAMS event glyph, else a generic fallback. */
function EventGlyph({ type }: { type: string }) {
  const name = eventIconName(type);
  if (Icons.eventIconUrl(name)) return <Icons.EventIcon name={name} size={22} />;
  const t = type.toLowerCase();
  if (t.includes('speed')) return <Icons.Speedometer03 size={18} />;
  if (t.includes('brak')) return <Icons.AlertOctagon size={18} />;
  if (t.includes('idl')) return <Icons.AlertTriangle size={18} />;
  return <Icons.AlertCircle size={18} />;
}

function defaultStyle(_type: string, crit: EventCriticality): EventStyle {
  return { icon: null, color: CRIT[crit] };
}

/* filter dropdown chip (presentational + optional options) */
function FilterChip({ icon, label, value, options, onSelect }: { icon: React.ReactNode; label: string; value?: string; options?: string[]; onSelect?: (v: string) => void }) {
  const [open, setOpen] = React.useState(false);
  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <button type="button" aria-haspopup="menu" aria-expanded={open} className="flex min-w-[150px] items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-left transition-colors hover:bg-muted/40">
          <span className="shrink-0 text-muted-foreground">{icon}</span>
          <span className="flex min-w-0 flex-1 flex-col">
            <span className="text-caption font-medium uppercase tracking-wide text-muted-foreground">{label}</span>
            <span className="truncate text-body-sm font-medium text-foreground">{value ?? 'All'}</span>
          </span>
          <Icons.ChevronDown size={15} className="shrink-0 text-muted-foreground" />
        </button>
      </PopoverTrigger>
      {options && (
        <PopoverContent align="start" className="max-h-64 w-[--radix-popover-trigger-width] overflow-auto p-1">
          {options.map((o) => (
            <button key={o} type="button" onClick={() => { onSelect?.(o); setOpen(false); }} className="flex w-full rounded-md px-2.5 py-2 text-left text-body-sm text-foreground transition-colors hover:bg-muted">{o}</button>
          ))}
        </PopoverContent>
      )}
    </Popover>
  );
}

function Chip({ icon, children }: { icon: React.ReactNode; children: React.ReactNode }) {
  return <span className="inline-flex items-center gap-1.5 rounded-md bg-muted/60 px-2 py-1 text-body-xs font-medium text-foreground"><span className="text-muted-foreground">{icon}</span><span className="truncate">{children}</span></span>;
}

function CritPill({ crit }: { crit: EventCriticality }) {
  const c = CRIT[crit];
  const label = crit === 'critical' ? 'Critical' : crit === 'warning' ? 'Warning' : 'Info';
  return <span className="inline-flex items-center gap-1 rounded-md px-2 py-0.5 text-caption font-bold" style={{ background: `color-mix(in srgb, ${c} 14%, transparent)`, color: c }}><Icons.Flag01 size={11} />{label}</span>;
}

function SpeedChart({ e, height = 150 }: { e: EventItem; height?: number }) {
  if (!e.speedSeries) return null;
  return (
    <div className="relative" style={{ height }}>
      <LineChart data={e.speedSeries} xKey="t" height={height} series={[{ dataKey: 'speed', name: 'Speed (km/h)', color: 'var(--primary)' }]} />
    </div>
  );
}

/* ── severity tab bar (All · Critical · High · Normal · Assigned to me) ─── */
type SeverityTab = 'All' | 'Critical' | 'High' | 'Normal' | 'Assigned to me';
const SEVERITY_TABS: SeverityTab[] = ['All', 'Critical', 'High', 'Normal', 'Assigned to me'];

function matchesSeverityTab(e: EventItem, tab: SeverityTab): boolean {
  switch (tab) {
    case 'Critical': return e.criticality === 'critical';
    case 'High': return e.criticality === 'warning';
    case 'Normal': return e.criticality === 'info';
    case 'Assigned to me': return e.assignedToMe === true;
    default: return true;
  }
}

/** Underline tab bar — mirrors the DS "aria-current tab" convention (see Subscriptions). */
function SeverityTabBar({ value, onChange, counts }: { value: SeverityTab; onChange: (v: SeverityTab) => void; counts: Record<SeverityTab, number> }) {
  return (
    <div className="flex flex-wrap items-center gap-5 border-b border-border">
      {SEVERITY_TABS.map((t) => {
        const active = value === t;
        return (
          <button
            key={t}
            type="button"
            onClick={() => onChange(t)}
            aria-current={active ? 'page' : undefined}
            className={cn('relative -mb-px flex items-center gap-1.5 pb-2.5 text-body-sm font-semibold transition-colors focus-visible:ring-2 focus-visible:ring-ring', active ? 'text-primary' : 'text-muted-foreground hover:text-foreground')}
          >
            {t}
            <span className={cn('rounded-full px-1.5 py-0.5 text-caption font-bold', active ? 'bg-primary/10 text-primary' : 'bg-muted text-muted-foreground')}>{counts[t]}</span>
            {active && <span className="absolute inset-x-0 bottom-0 h-0.5 rounded-full bg-primary" />}
          </button>
        );
      })}
    </div>
  );
}

/* ── map severity toggle overlay (Critical/High/Normal show-hide) ────────── */
const MAP_SEVERITY_TOGGLES: { key: EventCriticality; label: string }[] = [
  { key: 'critical', label: 'Critical' },
  { key: 'warning', label: 'High' },
  { key: 'info', label: 'Normal' },
];

function MapSeverityToggle({ visible, onChange }: { visible: Record<EventCriticality, boolean>; onChange: (key: EventCriticality, v: boolean) => void }) {
  return (
    <div className="absolute left-3 top-3 z-[400] flex items-center gap-4 rounded-lg border border-border bg-card px-3 py-2 shadow-sm">
      {MAP_SEVERITY_TOGGLES.map(({ key, label }) => (
        <label key={key} className="flex cursor-pointer items-center gap-1.5 text-body-xs font-medium text-foreground">
          <Checkbox checked={visible[key]} onCheckedChange={(v) => onChange(key, v === true)} aria-label={`Toggle ${label} markers`} />
          <span className="size-2 shrink-0 rounded-full" style={{ background: CRIT[key] }} />
          {label}
        </label>
      ))}
    </div>
  );
}

/* ── event card (collapsed + expanded) ──────────────────────────────────── */
function EventCard({
  e, style, expanded, checked, onToggle, onToggleCheck, onViewDetails, onAddComment, onAssign, onEscalate,
}: {
  e: EventItem; style: EventStyle; expanded: boolean; checked: boolean;
  onToggle: () => void; onToggleCheck: () => void;
  onViewDetails?: () => void; onAddComment?: () => void; onAssign?: () => void; onEscalate?: () => void;
}) {
  const border = e.criticality === 'critical' ? CRIT.critical : e.criticality === 'warning' ? CRIT.warning : 'transparent';
  return (
    <div
      className={cn('overflow-hidden rounded-xl border bg-card transition-shadow', expanded ? 'border-border shadow-sm' : 'border-border hover:shadow-sm')}
      style={{ borderLeft: `3px solid ${border}` }}
    >
      <div className="flex w-full items-start gap-3 p-3 text-left">
        <span className="mt-1 shrink-0" onClick={(ev) => ev.stopPropagation()}>
          <Checkbox checked={checked} onCheckedChange={() => onToggleCheck()} aria-label={`Select ${e.title}`} />
        </span>
        <button type="button" onClick={onToggle} aria-expanded={expanded} aria-label={`Toggle details for ${e.title}`} className="flex min-w-0 flex-1 items-start gap-3 text-left">
          <span className="grid size-11 shrink-0 place-items-center rounded-lg" style={{ background: `color-mix(in srgb, ${style.color} 12%, transparent)`, color: style.color }}>{style.icon ?? <EventGlyph type={e.type} />}</span>
          <div className="flex min-w-0 flex-1 flex-col gap-1.5">
            <div className="flex items-start gap-2">
              <span className="text-body font-semibold text-foreground">{e.title}</span>
              <span className="text-body-sm text-muted-foreground">{e.subtitle}</span>
              <span className="ml-auto shrink-0 text-body-xs text-muted-foreground">{e.timeLabel}</span>
            </div>
            <div className="flex flex-wrap items-center gap-1.5">
              <Chip icon={<Icons.Truck01 size={13} />}>{e.vehicle}</Chip>
              <Chip icon={<Icons.User01 size={13} />}>{e.person}</Chip>
              <Chip icon={<Icons.Flag01 size={13} />}>{e.zone}</Chip>
              <Chip icon={<Icons.MarkerPin01 size={13} />}>{e.location}</Chip>
              {e.metric && <span className="inline-flex items-center rounded-md px-2 py-1 text-body-xs font-semibold" style={{ background: `color-mix(in srgb, ${e.metric.tone ?? CRIT.warning} 16%, transparent)`, color: e.metric.tone ?? CRIT.warning }}>{e.metric.value}</span>}
            </div>
          </div>
        </button>
      </div>

      {expanded && (
        <div className="border-t border-border p-4">
          <div className="grid grid-cols-2 gap-x-8 gap-y-3">
            <DetailRow label="Criticality" value={<CritPill crit={e.criticality} />} />
            <DetailRow label="Status" value={<span className="inline-flex items-center rounded-md px-2 py-0.5 text-caption font-bold" style={{ background: `color-mix(in srgb, ${e.statusTone ?? 'var(--chart-accent-purple)'} 14%, transparent)`, color: e.statusTone ?? 'var(--chart-accent-purple)' }}>{e.status}</span>} />
            {e.details.map((d) => <DetailRow key={d.label} label={d.label} value={d.value} />)}
            {e.assignee && <DetailRow label="Assigned To" value={e.assignee} />}
          </div>
          <div className="mt-4 flex flex-wrap items-center justify-between gap-2">
            <div className="flex flex-wrap items-center gap-2">
              <button type="button" onClick={onAddComment} className="rounded-lg border border-border px-4 py-2 text-body-sm font-semibold text-foreground transition-colors hover:bg-muted">Add Comment</button>
              <button type="button" onClick={onAssign} className="rounded-lg border border-border px-4 py-2 text-body-sm font-semibold text-foreground transition-colors hover:bg-muted">Assign</button>
              <button type="button" onClick={onEscalate} className="rounded-lg border border-border px-4 py-2 text-body-sm font-semibold text-foreground transition-colors hover:bg-muted">Escalate</button>
            </div>
            <button type="button" onClick={onViewDetails} className="rounded-lg border border-primary px-4 py-2 text-body-sm font-semibold text-primary transition-colors hover:bg-primary/5">View Details</button>
          </div>
        </div>
      )}
    </div>
  );
}
function DetailRow({ label, value }: { label: string; value: React.ReactNode }) {
  return <div className="flex items-center justify-between gap-3"><span className="text-body-sm text-muted-foreground">{label}</span><span className="text-body-sm font-semibold text-foreground">{value}</span></div>;
}

export function EventsView({
  events, eventStyles, center = [25.18, 55.35], zoom = 12, onViewDetails, onAddComment, onAssign, onEscalate,
  onBulkAssign, onBulkEscalate, onBulkUpdateStatus, searchQuery, onSearchChange, className,
}: EventsViewProps) {
  const [expandedId, setExpandedId] = React.useState<string | null>(null);
  const [severityTab, setSeverityTab] = React.useState<SeverityTab>('All');
  const [typeFilter, setTypeFilter] = React.useState<string>('All');
  const [localQuery, setLocalQuery] = React.useState('');
  const [selectedIds, setSelectedIds] = React.useState<Set<string>>(new Set());
  const [severityVisible, setSeverityVisible] = React.useState<Record<EventCriticality, boolean>>({ critical: true, warning: true, info: true });
  const mapRef = React.useRef<LeafletMapHandle>(null);

  const query = searchQuery ?? localQuery;
  const setQuery = (v: string) => { if (onSearchChange) onSearchChange(v); else setLocalQuery(v); };

  const styleFor = React.useCallback((e: EventItem) => eventStyles?.[e.type] ?? defaultStyle(e.type, e.criticality), [eventStyles]);
  const types = React.useMemo(() => ['All', ...Array.from(new Set(events.map((e) => e.type)))], [events]);

  const matchesSearch = React.useCallback((e: EventItem) => {
    const q = query.trim().toLowerCase();
    if (!q) return true;
    return [e.title, e.subtitle, e.vehicle, e.person, e.zone, e.location].some((f) => f.toLowerCase().includes(q));
  }, [query]);

  // base set (type filter + search) used both for the final list and for the
  // severity-tab counts, so switching tabs never changes what the counts mean.
  const baseForCounts = React.useMemo(() => events.filter((e) =>
    (typeFilter === 'All' || e.type === typeFilter) && matchesSearch(e),
  ), [events, typeFilter, matchesSearch]);

  const counts: Record<SeverityTab, number> = {
    All: baseForCounts.length,
    Critical: baseForCounts.filter((e) => e.criticality === 'critical').length,
    High: baseForCounts.filter((e) => e.criticality === 'warning').length,
    Normal: baseForCounts.filter((e) => e.criticality === 'info').length,
    'Assigned to me': baseForCounts.filter((e) => e.assignedToMe).length,
  };

  const filtered = React.useMemo(() => baseForCounts.filter((e) => matchesSeverityTab(e, severityTab)), [baseForCounts, severityTab]);

  // group by dateGroup, preserving order
  const groups = React.useMemo(() => {
    const m = new Map<string, EventItem[]>();
    for (const e of filtered) (m.get(e.dateGroup) ?? m.set(e.dateGroup, []).get(e.dateGroup)!).push(e);
    return [...m.entries()];
  }, [filtered]);

  const expandedEvent = events.find((e) => e.id === expandedId) ?? null;

  const toggle = (e: EventItem) => {
    const next = expandedId === e.id ? null : e.id;
    setExpandedId(next);
    if (next) mapRef.current?.flyTo(e.position, 14);
  };

  // selection must reconcile to what's actually visible — a filter/search change
  // must drop selected ids that scrolled out of view, so the bulk bar + Select All
  // count never lie about what's on screen (see Subscriptions org-tab pattern).
  React.useEffect(() => {
    const filteredIds = new Set(filtered.map((e) => e.id));
    setSelectedIds((cur) => {
      const next = new Set([...cur].filter((id) => filteredIds.has(id)));
      return next.size === cur.size ? cur : next;
    });
  }, [filtered]);

  const toggleCheck = (id: string) => setSelectedIds((cur) => {
    const next = new Set(cur);
    if (next.has(id)) next.delete(id); else next.add(id);
    return next;
  });
  const clearSelection = () => setSelectedIds(new Set());
  const allSelected = filtered.length > 0 && filtered.every((e) => selectedIds.has(e.id));
  const toggleSelectAll = () => setSelectedIds(allSelected ? new Set() : new Set(filtered.map((e) => e.id)));

  // ordered by position in the filtered/date-grouped list, not click order —
  // so a bulk sheet/consumer sees selected events in on-screen order.
  const orderedSelectedIds = React.useMemo(() => filtered.filter((e) => selectedIds.has(e.id)).map((e) => e.id), [filtered, selectedIds]);

  // Assign only OPENS the assign sheet (async confirm inside it) — it must not
  // clear the selection before the user confirms. Escalate/Update Status are
  // synchronous bulk writes, so they clear the selection immediately after.
  const bulkAssign = () => onBulkAssign?.(orderedSelectedIds);
  const runBulk = (fn?: (ids: string[]) => void) => { fn?.(orderedSelectedIds); clearSelection(); };

  const markers = filtered.filter((e) => severityVisible[e.criticality]).map((e) => ({
    id: e.id,
    position: e.position,
    kind: 'dot' as const,
    status: (e.criticality === 'critical' ? 'critical' : e.criticality === 'warning' ? 'warning' : 'idle') as 'critical' | 'warning' | 'idle',
  }));

  return (
    <div className={cn('flex h-full min-h-0', className)}>
      {/* left: search + severity tabs + filters + list */}
      <div className="relative flex w-[620px] max-w-[54%] min-w-[440px] flex-col border-r border-border">
        <div className="flex flex-col gap-3 border-b border-border p-4">
          <div className="relative">
            <Icons.SearchMd size={15} className="pointer-events-none absolute left-2.5 top-1/2 z-10 -translate-y-1/2 text-muted-foreground" />
            <input
              value={query}
              onChange={(ev) => setQuery(ev.target.value)}
              placeholder="Search"
              aria-label="Search events"
              className="h-9 w-full rounded-lg border border-border bg-card pl-8 pr-3 text-body-sm outline-none placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring"
            />
          </div>

          <SeverityTabBar value={severityTab} onChange={setSeverityTab} counts={counts} />

          <div className="flex flex-wrap gap-2.5">
            <FilterChip icon={<Icons.Truck01 size={16} />} label="Assets" value="2 Items Selected" />
            <FilterChip icon={<Icons.Users01 size={16} />} label="Workforce" value="2 Persons Selected" />
            <FilterChip icon={<Icons.Calendar size={16} />} label="Date Range" value="23-02 to 24-06" />
          </div>
          <div className="flex flex-wrap gap-2.5">
            <FilterChip icon={<Icons.Flag01 size={16} />} label="Events" value={typeFilter} options={types} onSelect={setTypeFilter} />
            <FilterChip icon={<Icons.MarkerPin01 size={16} />} label="Zone" />
            <FilterChip icon={<Icons.MarkerPin01 size={16} />} label="Location" />
          </div>
        </div>

        <div className="min-h-0 flex-1 space-y-4 overflow-auto p-4 pb-16">
          <div className="flex items-center justify-between">
            <span className="text-body-xs text-muted-foreground">Showing <span className="font-semibold text-foreground">{filtered.length}</span> event{filtered.length === 1 ? '' : 's'}</span>
            {filtered.length > 0 && (
              <button type="button" onClick={toggleSelectAll} className="rounded-sm text-body-xs font-semibold text-primary hover:underline focus-visible:ring-2 focus-visible:ring-ring">
                {allSelected ? 'Clear Selection' : `Select All (${filtered.length})`}
              </button>
            )}
          </div>
          {groups.map(([group, items]) => (
            <div key={group} className="space-y-2.5">
              <div className="flex items-center justify-between">
                <span className="text-body-sm font-semibold text-muted-foreground">{group}</span>
                <span className="text-body-xs text-muted-foreground">{items.length} Events</span>
              </div>
              {items.map((e) => (
                <EventCard
                  key={e.id}
                  e={e}
                  style={styleFor(e)}
                  expanded={expandedId === e.id}
                  checked={selectedIds.has(e.id)}
                  onToggle={() => toggle(e)}
                  onToggleCheck={() => toggleCheck(e.id)}
                  onViewDetails={() => onViewDetails?.(e)}
                  onAddComment={() => onAddComment?.(e)}
                  onAssign={() => onAssign?.(e)}
                  onEscalate={() => onEscalate?.(e)}
                />
              ))}
            </div>
          ))}
          {!groups.length && <p className="py-10 text-center text-body-sm text-muted-foreground">No events match the filters.</p>}
        </div>

        {selectedIds.size > 0 && (
          <div role="status" aria-live="polite" className="absolute inset-x-0 bottom-4 z-[500] mx-auto flex w-fit max-w-[92%] items-center gap-3 rounded-xl border border-border bg-card px-4 py-3 shadow-lg">
            <button type="button" aria-label="Clear selection" onClick={clearSelection} className="grid size-6 shrink-0 place-items-center rounded-md text-muted-foreground transition-colors hover:bg-muted focus-visible:ring-2 focus-visible:ring-ring"><Icons.XClose size={16} /></button>
            <span className="shrink-0 text-body-sm font-medium text-foreground">{selectedIds.size} Event{selectedIds.size === 1 ? '' : 's'} selected</span>
            <button type="button" onClick={bulkAssign} className="shrink-0 rounded-lg border border-border px-3 py-1.5 text-body-sm font-semibold text-foreground transition-colors hover:bg-muted">Assign</button>
            <button type="button" onClick={() => runBulk(onBulkEscalate)} className="shrink-0 rounded-lg border px-3 py-1.5 text-body-sm font-semibold transition-colors hover:bg-muted/40" style={{ borderColor: 'var(--status-warning)', color: 'var(--status-warning)' }}>Escalate</button>
            <button type="button" onClick={() => runBulk(onBulkUpdateStatus)} className="shrink-0 rounded-lg bg-primary px-3 py-1.5 text-body-sm font-semibold text-primary-foreground transition-colors hover:bg-primary/90">Update Status</button>
          </div>
        )}
      </div>

      {/* right: map + severity toggle + contextual widget */}
      <div className="relative min-h-0 flex-1">
        <LeafletMap ref={mapRef} center={center} zoom={zoom} markers={markers} zoomControl className="h-full w-full" />
        <MapSeverityToggle visible={severityVisible} onChange={(key, v) => setSeverityVisible((cur) => ({ ...cur, [key]: v }))} />
        {expandedEvent?.speedSeries && (
          <div className="absolute bottom-4 right-4 z-[400] w-[380px] rounded-xl border border-border bg-card p-3 shadow-lg">
            <div className="mb-1 flex items-center gap-2">
              <Icons.Speedometer03 size={15} className="text-primary" />
              <span className="text-body-sm font-semibold text-foreground">{expandedEvent.title}</span>
              <span className="ml-auto truncate text-body-xs text-muted-foreground">{expandedEvent.location}</span>
            </div>
            <div style={{ width: 356, height: 140 }}>
              <SpeedChart e={expandedEvent} height={140} />
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
