/**
 * weatherForecastData.ts — the Live Monitoring weather layer's forecast panel
 * data, copied VERBATIM (2026-09-01 Live GIS parity run) from
 * `tenants/uccp/modules/live-monitoring/blueprint.json` →
 * `uiConfig.map.weather.forecast`, which is the exact object LM feeds its
 * `WeatherForecastPanel`. Generated by `tools/seeds/gen-weather-stations.mjs`
 * on the LM side; inlined here rather than imported because the cockpit is an
 * isolated React-18 bundle and that blueprint is a ~700 KB file the cockpit
 * has no other use for.
 *
 * Same location, same 10 days, same hourly rows, same QMD outlook — so the
 * Live GIS forecast panel and Live Monitoring's read identically.
 *
 * Shape mirrors the design system's `packages/v5-templates/src/map/
 * weather-types.ts`.
 */

/** One hour column in the Open-Meteo grid. */
export interface WeatherForecastRow {
  time: string
  tempC: number
  precipitationMm: number
  precipitationChance: number
  windKmh: number
}
/** One day in the Open-Meteo grid — a header spanning its hour columns. */
export interface WeatherForecastDay {
  day: string
  hours: WeatherForecastRow[]
}
/** One day column in the QMD 10-day official outlook. */
export interface WeatherDailyRow {
  date: string
  warning: string
  minC: number
  maxC: number
  rainMm?: number
}
export interface WeatherForecastLocation {
  label: string
  coordinates?: string
  sunrise?: string
  sunset?: string
  elevation?: string
}
export interface WeatherForecastPanelData {
  location?: WeatherForecastLocation
  openMeteo?: WeatherForecastDay[]
  qmd?: WeatherDailyRow[]
}

export const WEATHER_FORECAST: WeatherForecastPanelData = {
  "location": {
    "label": "Doha, Qatar (+03:00)",
    "coordinates": "25.285° N, 51.531° E",
    "sunrise": "5:12 AM",
    "sunset": "5:58 PM",
    "elevation": "10 m (33 ft)"
  },
  "openMeteo": [
    {
      "day": "Sun 31 Aug",
      "hours": [
        {
          "time": "08:00",
          "tempC": 31.7,
          "precipitationMm": 0,
          "precipitationChance": 0,
          "windKmh": 11.2
        },
        {
          "time": "14:00",
          "tempC": 41.9,
          "precipitationMm": 0,
          "precipitationChance": 0,
          "windKmh": 7.6
        },
        {
          "time": "20:00",
          "tempC": 32.7,
          "precipitationMm": 0,
          "precipitationChance": 1,
          "windKmh": 6.8
        }
      ]
    },
    {
      "day": "Mon 01 Sep",
      "hours": [
        {
          "time": "08:00",
          "tempC": 31.2,
          "precipitationMm": 0.03,
          "precipitationChance": 2,
          "windKmh": 19.4
        },
        {
          "time": "14:00",
          "tempC": 41.8,
          "precipitationMm": 1.24,
          "precipitationChance": 20,
          "windKmh": 17.4
        },
        {
          "time": "20:00",
          "tempC": 33.1,
          "precipitationMm": 0.26,
          "precipitationChance": 5,
          "windKmh": 9.6
        }
      ]
    },
    {
      "day": "Tue 02 Sep",
      "hours": [
        {
          "time": "08:00",
          "tempC": 32.8,
          "precipitationMm": 0.46,
          "precipitationChance": 25,
          "windKmh": 12.8
        },
        {
          "time": "14:00",
          "tempC": 39.4,
          "precipitationMm": 9.11,
          "precipitationChance": 52,
          "windKmh": 6.9
        },
        {
          "time": "20:00",
          "tempC": 33.1,
          "precipitationMm": 0.59,
          "precipitationChance": 27,
          "windKmh": 15
        }
      ]
    },
    {
      "day": "Wed 03 Sep",
      "hours": [
        {
          "time": "08:00",
          "tempC": 32.8,
          "precipitationMm": 0,
          "precipitationChance": 5,
          "windKmh": 21.5
        },
        {
          "time": "14:00",
          "tempC": 42,
          "precipitationMm": 0,
          "precipitationChance": 3,
          "windKmh": 20.8
        },
        {
          "time": "20:00",
          "tempC": 32.7,
          "precipitationMm": 0,
          "precipitationChance": 1,
          "windKmh": 15.7
        }
      ]
    },
    {
      "day": "Thu 04 Sep",
      "hours": [
        {
          "time": "08:00",
          "tempC": 34.8,
          "precipitationMm": 0,
          "precipitationChance": 4,
          "windKmh": 33.5
        },
        {
          "time": "14:00",
          "tempC": 35.4,
          "precipitationMm": 38.16,
          "precipitationChance": 94,
          "windKmh": 40.8
        },
        {
          "time": "20:00",
          "tempC": 31.4,
          "precipitationMm": 0,
          "precipitationChance": 7,
          "windKmh": 15.4
        }
      ]
    },
    {
      "day": "Fri 05 Sep",
      "hours": [
        {
          "time": "08:00",
          "tempC": 32.8,
          "precipitationMm": 2.72,
          "precipitationChance": 47,
          "windKmh": 14.1
        },
        {
          "time": "14:00",
          "tempC": 34.2,
          "precipitationMm": 10.25,
          "precipitationChance": 76,
          "windKmh": 22.9
        },
        {
          "time": "20:00",
          "tempC": 31.9,
          "precipitationMm": 0.32,
          "precipitationChance": 47,
          "windKmh": 15.1
        }
      ]
    },
    {
      "day": "Sat 06 Sep",
      "hours": [
        {
          "time": "08:00",
          "tempC": 34.3,
          "precipitationMm": 2,
          "precipitationChance": 31,
          "windKmh": 17.7
        },
        {
          "time": "14:00",
          "tempC": 42.1,
          "precipitationMm": 4.49,
          "precipitationChance": 49,
          "windKmh": 10.6
        },
        {
          "time": "20:00",
          "tempC": 32.5,
          "precipitationMm": 1.87,
          "precipitationChance": 28,
          "windKmh": 9.9
        }
      ]
    },
    {
      "day": "Sun 07 Sep",
      "hours": [
        {
          "time": "08:00",
          "tempC": 32.1,
          "precipitationMm": 0,
          "precipitationChance": 2,
          "windKmh": 18.9
        },
        {
          "time": "14:00",
          "tempC": 42,
          "precipitationMm": 0,
          "precipitationChance": 1,
          "windKmh": 16.9
        },
        {
          "time": "20:00",
          "tempC": 31.2,
          "precipitationMm": 0,
          "precipitationChance": 5,
          "windKmh": 9.8
        }
      ]
    },
    {
      "day": "Mon 08 Sep",
      "hours": [
        {
          "time": "08:00",
          "tempC": 31.8,
          "precipitationMm": 0.21,
          "precipitationChance": 11,
          "windKmh": 19.6
        },
        {
          "time": "14:00",
          "tempC": 39.6,
          "precipitationMm": 1.61,
          "precipitationChance": 38,
          "windKmh": 8.7
        },
        {
          "time": "20:00",
          "tempC": 32.3,
          "precipitationMm": 0.44,
          "precipitationChance": 5,
          "windKmh": 15.8
        }
      ]
    },
    {
      "day": "Tue 09 Sep",
      "hours": [
        {
          "time": "08:00",
          "tempC": 34.3,
          "precipitationMm": 0,
          "precipitationChance": 5,
          "windKmh": 18.9
        },
        {
          "time": "14:00",
          "tempC": 39.5,
          "precipitationMm": 0,
          "precipitationChance": 8,
          "windKmh": 13.8
        },
        {
          "time": "20:00",
          "tempC": 32.9,
          "precipitationMm": 0,
          "precipitationChance": 5,
          "windKmh": 20.9
        }
      ]
    }
  ],
  "qmd": [
    {
      "date": "Sun 31 Aug",
      "warning": "Hot",
      "minC": 34.1,
      "maxC": 39.4,
      "rainMm": 0
    },
    {
      "date": "Mon 01 Sep",
      "warning": "Rain Expected",
      "minC": 34.2,
      "maxC": 37.6,
      "rainMm": 0.5
    },
    {
      "date": "Tue 02 Sep",
      "warning": "Rain Expected",
      "minC": 33.4,
      "maxC": 36.6,
      "rainMm": 6.2
    },
    {
      "date": "Wed 03 Sep",
      "warning": "Fine",
      "minC": 34.4,
      "maxC": 41.2,
      "rainMm": 0
    },
    {
      "date": "Thu 04 Sep",
      "warning": "Storm Warning",
      "minC": 31.1,
      "maxC": 36.6,
      "rainMm": 38.5
    },
    {
      "date": "Fri 05 Sep",
      "warning": "Heavy Rain Warning",
      "minC": 31.8,
      "maxC": 37.6,
      "rainMm": 18.3
    },
    {
      "date": "Sat 06 Sep",
      "warning": "Rain Expected",
      "minC": 32.3,
      "maxC": 34.2,
      "rainMm": 8.3
    },
    {
      "date": "Sun 07 Sep",
      "warning": "Hot",
      "minC": 33.3,
      "maxC": 38.9,
      "rainMm": 0
    },
    {
      "date": "Mon 08 Sep",
      "warning": "Rain Expected",
      "minC": 30.8,
      "maxC": 36.3,
      "rainMm": 1.7
    },
    {
      "date": "Tue 09 Sep",
      "warning": "Hot",
      "minC": 31,
      "maxC": 40.1,
      "rainMm": 0
    }
  ]
}
